### ISSUE TITLE
Torque vector in wrong direction

### ISSUE THREAD

**Issue by fslanovc** [magpylib/magpylib-force#4]
I believe we have a sign error in the torque vector. This makes the magnets rotate in the wrong direction.

![0](https://github.com/magpylib/magpylib-force/assets/52533009/c9568845-f8a5-46a7-bb7d-9e0601342770)

Maybe the cross product mu x B is calculated in the wrong order somewhere in the code.

**Comment by OrtnerMichael** [comment]
fixed in #6
